name: visinity
channels:
  - conda-forge
dependencies:
  - python=3.9
  - appdirs=1.4.4
  - Flask=2.3.2
  - flask-sqlalchemy=3.0.2
  - hdbscan=0.8.28
  - llvmlite=0.39.1
  - joblib=1.1.0
  - matplotlib=3.8.2
  - numba=0.56.4
  - numpy=1.23.5
  - orjson=3.9.10
  - pandas=2.2.0
  - pillow=8.1.1
  - requests=2.31.0
  - scikit-learn=1.1.2
  - scikit-image=0.19.3
  - scipy=1.12.0
  - tifffile=2021.4.8
  - waitress=2.1.2
  - zarr=2.10.1
  - pyinstaller=6.3.0
  - pip
  - pip:
      - elementpath==2.3.2
      - palom==2024.4.1
      - pycave==3.1.3
      - pydantic==1.10.2
      - numpy-indexed==0.3.7
      - ome-types==0.2.9
      - opencv-python==4.9.0.80
      - umap-learn==0.5.5
      - xmlschema==1.8.0
      - imagecodecs[all]

